// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhFS3Fmp5qU-jb5S7FbRqNw7L4kC0_eDk',
    appId: '1:107226254817:android:e5d8de8c618ed5e7bcd6a0',
    messagingSenderId: '107226254817',
    projectId: 'exception-b2543',
    databaseURL: 'https://exception-b2543-default-rtdb.firebaseio.com',
    storageBucket: 'exception-b2543.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR3n8XELKJletmQqbDeDVdW7BiiHzaYAE',
    appId: '1:107226254817:ios:fb5f54e375865f53bcd6a0',
    messagingSenderId: '107226254817',
    projectId: 'exception-b2543',
    databaseURL: 'https://exception-b2543-default-rtdb.firebaseio.com',
    storageBucket: 'exception-b2543.appspot.com',
    iosClientId: '107226254817-5ni3kc3qlij5ngc8pmb18on6889t15du.apps.googleusercontent.com',
    iosBundleId: 'com.example.exception',
  );
}
